version: 1.0.{build}
image: Visual Studio 2017
build_script:
- cmd: 
    dotnet build Fody.sln --configuration Release

    msbuild Integration\Integration.sln /p:Configuration=Release /verbosity:minimal

    msbuild Integration\Tests\Tests.csproj /target:Restore
test:
  assemblies:
    - '**\*Tests.dll'
artifacts:
- path: nugets\*.nupkg

#install:
#  - ps: $blockRdp = $true; iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))
on_finish:
  - ps: $blockRdp = $true; iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))
